id: I94927449
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T16:07:09+00:00'
last_modified: '2022-06-07T17:39:14.488517+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD45496
  title: གསུང་འབུམ། རིན་ཆེན་གྲུབ ༼བྲིས་མ༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '6100':
      image_group_id: I2DB62459
      title: ''
      total_pages: 646
      order: 1
      base_file: 6100.txt
    '0035':
      image_group_id: I2DB62460
      title: ''
      total_pages: 738
      order: 2
      base_file: 0035.txt
    BD54:
      image_group_id: I2DB62461
      title: ''
      total_pages: 872
      order: 3
      base_file: BD54.txt
    '3630':
      image_group_id: I2DB62462
      title: ''
      total_pages: 1112
      order: 4
      base_file: 3630.txt
    61B4:
      image_group_id: I2DB62463
      title: ''
      total_pages: 718
      order: 5
      base_file: 61B4.txt
    '6602':
      image_group_id: I2DB62464
      title: ''
      total_pages: 1160
      order: 6
      base_file: 6602.txt
    DDDD:
      image_group_id: I2DB62465
      title: ''
      total_pages: 1240
      order: 7
      base_file: DDDD.txt
    806D:
      image_group_id: I2DB62466
      title: ''
      total_pages: 1134
      order: 8
      base_file: 806D.txt
    B04D:
      image_group_id: I2DB62467
      title: ''
      total_pages: 992
      order: 9
      base_file: B04D.txt
    B050:
      image_group_id: I2DB62468
      title: ''
      total_pages: 948
      order: 10
      base_file: B050.txt
    2EED:
      image_group_id: I2DB62469
      title: ''
      total_pages: 930
      order: 11
      base_file: 2EED.txt
    0A13:
      image_group_id: I2DB62470
      title: ''
      total_pages: 916
      order: 12
      base_file: 0A13.txt
    92EB:
      image_group_id: I2DB62471
      title: ''
      total_pages: 1154
      order: 13
      base_file: 92EB.txt
    FAFE:
      image_group_id: I2DB62472
      title: ''
      total_pages: 1416
      order: 14
      base_file: FAFE.txt
    048D:
      image_group_id: I2DB62473
      title: ''
      total_pages: 1270
      order: 15
      base_file: 048D.txt
    FAFA:
      image_group_id: I2DB62474
      title: ''
      total_pages: 902
      order: 16
      base_file: FAFA.txt
    '5879':
      image_group_id: I2DB62475
      title: ''
      total_pages: 848
      order: 17
      base_file: 5879.txt
    86EC:
      image_group_id: I2DB62476
      title: ''
      total_pages: 952
      order: 18
      base_file: 86EC.txt
    B7D7:
      image_group_id: I2DB62477
      title: ''
      total_pages: 744
      order: 19
      base_file: B7D7.txt
    43A9:
      image_group_id: I2DB62478
      title: ''
      total_pages: 1044
      order: 20
      base_file: 43A9.txt
    '7386':
      image_group_id: I2DB62479
      title: ''
      total_pages: 1272
      order: 21
      base_file: 7386.txt
    FFEE:
      image_group_id: I2DB62480
      title: ''
      total_pages: 898
      order: 22
      base_file: FFEE.txt
    ACA4:
      image_group_id: I2DB62481
      title: ''
      total_pages: 1282
      order: 23
      base_file: ACA4.txt
    091A:
      image_group_id: I2DB62482
      title: ''
      total_pages: 1422
      order: 24
      base_file: 091A.txt
    888B:
      image_group_id: I2DB62483
      title: ''
      total_pages: 1406
      order: 25
      base_file: 888B.txt
    4A1A:
      image_group_id: I2DB62484
      title: ''
      total_pages: 918
      order: 26
      base_file: 4A1A.txt
    '6090':
      image_group_id: I2DB62485
      title: ''
      total_pages: 846
      order: 27
      base_file: 6090.txt
    9ABB:
      image_group_id: I2DB62486
      title: ''
      total_pages: 838
      order: 28
      base_file: 9ABB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
